### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [UlyssesZh/ulyssesys#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by UlyssesZh** [comment]
I did not intend to get this theme added to an awesome list, but I am glad you'd like to do so! I added screenshots in 5608504.

By the way, how did you notice that I created a theme?
